### ISSUE TITLE
[1.16] blue_skies 引起的未知NPE

### ISSUE THREAD

**Issue by DPurple** [DPurple/LoliServer1.16#1]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** git version

**Operating System(操作系统) :** Windows Server 2008R2

**Concerned mod / plugin(有关的插件/Mod) :** blue skies

**Logs :** 
```
java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31) ~[?:?] {re:classloading}
	at com.legacy.blue_skies.entities.hostile.boss.StarlitCrusherEntity$SpewterSpawnAttackGoal.func_75246_d(StarlitCrusherEntity.java:1861) ~[blue_skies:1.1.3] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:392) ~[performant:1.16.2-5-3.72m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:764) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:locusazzurro_icaruswings.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2863) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityLadderMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:locusazzurro_icaruswings.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(MonsterEntity.java:43) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MonsterEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityLadderMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:350) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:locusazzurro_icaruswings.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.legacy.blue_skies.entities.util.base.SkiesBossEntity.func_70071_h_(SkiesBossEntity.java:109) ~[blue_skies:1.1.3] {re:mixin,re:classloading}
	at com.legacy.blue_skies.entities.hostile.boss.StarlitCrusherEntity.func_70071_h_(StarlitCrusherEntity.java:252) ~[blue_skies:1.1.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:823) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:752) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:571) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1032) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}
```

**Steps to Reproduce(复现步骤) :**
原因未知所以无法复现

**Description of issue :** 非公开issues, 尝试针对此问题进行防御

**Comment by DPurple** [comment]
之前询问过blue_skies的作者 他们说他们已经不想碰1.16的版本了 所以针对此问题只能在自己的服务器上进行防御
