### ISSUE TITLE
[1.16] 曾经出现过奇怪的ConcurrentModificationException

### ISSUE THREAD

**Issue by DPurple** [DPurple/LoliServer1.16#2]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** not loliserver

**Operating System(操作系统) :** Windows Server 2008R2

**Concerned mod / plugin(有关的插件/Mod) :** unknown

**Logs :**
```
[00:14:40] [Worker-Main-4/WARN] [net.minecraft.util.Util/]: Worker-Main-4 died
[00:14:40] [Worker-Main-4/ERROR] [net.minecraft.util.Util/]: Caught exception in thread Thread[Worker-Main-4,5,main]
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1661) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223117_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215603_b(SourceFile:170) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223119_a(SourceFile:108) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(DelegatedTaskExecutor.java:89) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(DelegatedTaskExecutor.java:133) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(DelegatedTaskExecutor.java:101) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

**Steps to Reproduce(复现步骤) :**
难以复现

**Description of issue :**
情况是:
Worker线程抛出异常, 没有被很好的捕捉，导致Worker线程直接停止, 这使得在Server线程中经常被使用的
ThreadTaskExecutor.managedBlock()造成了锁死 使服务器主线程失去了响应
此时其他线程还处于工作状态(还能聊天)

目前的做法是针对managedBlock()进行了简单的锁死检测, 在发生锁死时抛出异常来使服务器停止
更需要做的是对Worker进行异常捕获, 或选择容错或选择停止服务器
本次发生异常的部分似乎属于光线计算，所以我认为仅针对这次异常进行容错是没有问题的， 但是考虑到Worker本身是很基础的组件， 所以进行捕获异常可能会导致更严重的问题产生，所以还是仅针对managedBlock()进行锁死检测

**Comment by DPurple** [comment]
9月6日出现的锁死, 原因可能如下
```
java.base@16.0.2/jdk.internal.misc.Unsafe.park(Native Method)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1860)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3127)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1894)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2113)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:134)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.World.func_217353_a(World.java:272)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:113)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.World.func_212866_a_(World.java:268)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.World.func_180495_p(World.java:551)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getType(CraftBlock.java:214)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getState(CraftBlock.java:316)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onIceMelt(ResidenceBlockListener.java:301)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.lang.reflect.Method.invoke(Method.java:567)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.block.FireBlock.func_196271_a(FireBlock.java:94)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template.func_237141_a_(Template.java:360)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template$$Lambda$29829/0x00000008042a7458.consume(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.util.math.shapes.VoxelShapePart.func_211541_a(SourceFile:313)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.util.math.shapes.VoxelShapePart.func_211540_a(SourceFile:283)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template.func_222857_a(Template.java:350)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:314)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template.func_237152_b_(Template.java:203)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.template.Template.func_237144_a_(Template.java:199)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.mde.dungeons.world.structure.PiglinbarterStructure$FeatureRegisterHandler$1.generate(PiglinbarterStructure.java:73)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.mde.dungeons.world.structure.PiglinbarterStructure$FeatureRegisterHandler$1.func_241855_a(PiglinbarterStructure.java:45)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$29754/0x0000000804294230.accept(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.gen.ChunkGenerator.func_230351_a_(ChunkGenerator.java:220)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.ChunkStatus$$Lambda$2431/0x0000000801552348.doWork(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$18(ChunkManager.java:552)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.server.ChunkManager$$Lambda$29490/0x0000000804236d00.apply(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:550)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.server.ChunkManager$$Lambda$29487/0x0000000804236680.apply(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$29460/0x00000008042279d8.run(Unknown Source)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(DelegatedTaskExecutor.java:94)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(DelegatedTaskExecutor.java:138)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		net.minecraft.util.concurrent.DelegatedTaskExecutor.run(DelegatedTaskExecutor.java:106)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[14:17:00] [Spigot Watchdog Thread/ERROR] [Minecraft/]: 		java.base@16.0.2/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
这次Worker并没有抛异常, 但是看起来他已经锁死了

**Comment by DPurple** [comment]
尝试合理规划 max-tick-time 来防止锁死
